### ISSUE TITLE
Parsing time error

### ISSUE THREAD

**Issue by HansVanEijsden** [Ajnasz/letsencrypt-expiring-certs#1]
Thanks for the script!
Although, I cannot get it to work. Something to do with the system time?
# ./letsencrypt-expiring-certs -expire="`date`"

2016/03/23 16:50:35 parsing time "wo mrt 23 16:50:35 CET 2016" as "Mon Jan _2 15:04:05 MST 2006": cannot parse "wo mrt 23 16:50:35 CET 2016" as "Mon"
# ./letsencrypt-expiring-certs -expire="`date --date='2 weeks'`"

2016/03/23 16:50:47 parsing time "wo apr  6 17:50:47 CEST 2016" as "Mon Jan _2 15:04:05 MST 2006": cannot parse "wo apr  6 17:50:47 CEST 2016" as "Mon"
# ./letsencrypt-expiring-certs -expire="`date --date '03/05/2016 11:28'`"

2016/03/23 16:50:52 parsing time "za mrt  5 11:28:00 CET 2016" as "Mon Jan _2 15:04:05 MST 2006": cannot parse "za mrt  5 11:28:00 CET 2016" as "Mon"
# uname -a

Linux vps 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.5-1~bpo8+1 (2016-02-23) x86_64 GNU/Linux
# locale

LANG=nl_NL
LANGUAGE=
LC_CTYPE="nl_NL"
LC_NUMERIC="nl_NL"
LC_TIME="nl_NL"
LC_COLLATE="nl_NL"
LC_MONETARY="nl_NL"
LC_MESSAGES="nl_NL"
LC_PAPER="nl_NL"
LC_NAME="nl_NL"
LC_ADDRESS="nl_NL"
LC_TELEPHONE="nl_NL"
LC_MEASUREMENT="nl_NL"
LC_IDENTIFICATION="nl_NL"
LC_ALL=
# cat /etc/issue.net

Debian GNU/Linux 8

**Comment by Ajnasz** [comment]
Hey!

Could you try by using the following format: `'%a %b %d %T %Z %Y'`?

`./letsencrypt-expiring-certs -expire="$(date +'%a %b %d %T %Z %Y' --date='2 weeks')"`
`./letsencrypt-expiring-certs -expire="$(date +'%a %b %d %T %Z %Y' --date='3/05/2016 11:28')"`

and so on

**Comment by Ajnasz** [comment]
Actually maybe it will be still wrong, because the weekday and month name will be different in you locale. Let me know, and if that's the case I will add another date format to parse.

**Comment by HansVanEijsden** [comment]
Thanks for your quick reply. I tried it, but unfortunately still the same error:

# ./letsencrypt-expiring-certs -expire="$(date +'%a %b %d %T %Z %Y' --date='2 weeks')"

2016/03/23 17:24:06 parsing time "wo apr 06 18:24:06 CEST 2016" as "Mon Jan _2 15:04:05 MST 2006": cannot parse "wo apr 06 18:24:06 CEST 2016" as "Mon"

# ./letsencrypt-expiring-certs -expire="$(date +'%a %b %d %T %Z %Y' --date='3/05/2016 11:28')"

2016/03/23 17:24:12 parsing time "za mrt 05 11:28:00 CET 2016" as "Mon Jan _2 15:04:05 MST 2006": cannot parse "za mrt 05 11:28:00 CET 2016" as "Mon"

But... I found that lets encrypt-auto supports renew now of all the domains, just like your script.

I entered this in my crontab:
30 2 \* \* 1 /root/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log
35 2 \* \* 1 /bin/systemctl reload nginx

See step 4 here: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04
So, I think I don't need your script anymore, but I'm happy to keep helping here.

**Comment by Ajnasz** [comment]
Thank you, good to know! :)
